// Generated by design/scripts/generate.mjs — do not edit.
package net.soundpush.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object Tokens {
    object Light {
        val background = Color(0xFFF7F7F8)
        val surface = Color(0xFFFFFFFF)
        val surfaceMuted = Color(0xFFEFEFF2)
        val border = Color(0xFFE2E2E7)
        val textPrimary = Color(0xFF16161A)
        val textSecondary = Color(0xFF5C5C66)
        val accent = Color(0xFF2860E6)
        val onAccent = Color(0xFFFFFFFF)
        val success = Color(0xFF1E8E4E)
        val warning = Color(0xFFA15C00)
        val danger = Color(0xFFC62828)
        val micLive = Color(0xFFD93025)
    }

    object Dark {
        val background = Color(0xFF0F0F12)
        val surface = Color(0xFF18181C)
        val surfaceMuted = Color(0xFF222228)
        val border = Color(0xFF2C2C33)
        val textPrimary = Color(0xFFF2F2F5)
        val textSecondary = Color(0xFFA3A3AD)
        val accent = Color(0xFF6E97FF)
        val onAccent = Color(0xFF0B0B0E)
        val success = Color(0xFF4CC37E)
        val warning = Color(0xFFE8A73D)
        val danger = Color(0xFFF2685F)
        val micLive = Color(0xFFFF6B61)
    }

    object Space {
        val xs = 4.dp
        val sm = 8.dp
        val md = 16.dp
        val lg = 24.dp
        val xl = 32.dp
    }

    object Radius {
        val card = 12.dp
        val control = 8.dp
        val pill = 999.dp
    }

    object Type {
        val titleSize = 20.sp
        val titleLine = 28.sp
        const val titleWeight = 600
        val bodySize = 14.sp
        val bodyLine = 20.sp
        const val bodyWeight = 400
        val captionSize = 12.sp
        val captionLine = 16.sp
        const val captionWeight = 400
    }

    object Motion {
        const val fast = 150
        const val normal = 200
    }
}
