#!/usr/bin/env node
// Generates platform theme files from design/tokens/tokens.json:
//   - sound-push-desktop/ui/src/lib/theme/tokens.css  (CSS variables, Light / Dark / System)
//   - sound-push-mobile/android/core-ui/src/main/java/net/soundpush/ui/theme/Tokens.kt
// Run: node design/scripts/generate.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const tokens = JSON.parse(readFileSync(join(root, "design/tokens/tokens.json"), "utf8"));

const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());
const header = "Generated by design/scripts/generate.mjs — do not edit.";

// ---------------------------------------------------------------- contrast check (WCAG AA)
function luminance(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  const lin = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}
function contrast(a, b) {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
}
const pairs = [
  ["textPrimary", "background", 4.5],
  ["textPrimary", "surface", 4.5],
  ["textSecondary", "surface", 4.5],
  ["onAccent", "accent", 4.5],
  ["accent", "surface", 3.0],
  ["danger", "surface", 3.0],
  ["success", "surface", 3.0],
];
let failed = false;
for (const mode of ["light", "dark"]) {
  for (const [fg, bg, min] of pairs) {
    const ratio = contrast(tokens.color[mode][fg], tokens.color[mode][bg]);
    if (ratio < min) {
      console.error(`contrast ${mode} ${fg}/${bg} = ${ratio.toFixed(2)} < ${min}`);
      failed = true;
    }
  }
}
if (failed) process.exit(1);

// ---------------------------------------------------------------- CSS
const vars = (mode) =>
  Object.entries(tokens.color[mode])
    .map(([k, v]) => `  --color-${kebab(k)}: ${v};`)
    .join("\n");
const scale = [
  ...Object.entries(tokens.spacing).map(([k, v]) => `  --space-${k}: ${v}px;`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v}px;`),
  ...Object.entries(tokens.typography).flatMap(([k, v]) => [
    `  --font-${k}-size: ${v.size}px;`,
    `  --font-${k}-weight: ${v.weight};`,
    `  --font-${k}-line: ${v.lineHeight}px;`,
  ]),
  ...Object.entries(tokens.motion).map(([k, v]) => `  --motion-${k}: ${v}ms;`),
].join("\n");

const css = `/* ${header} */
:root {
${scale}
${vars("light")}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${vars("dark").replace(/^/gm, "  ")}
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
${vars("dark")}
  color-scheme: dark;
}
@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-fast: 0ms;
    --motion-normal: 0ms;
  }
}
`;
const cssPath = join(root, "sound-push-desktop/ui/src/lib/theme/tokens.css");
mkdirSync(dirname(cssPath), { recursive: true });
writeFileSync(cssPath, css);

// ---------------------------------------------------------------- Kotlin
const kColor = (hex) => `Color(0xFF${hex.slice(1).toUpperCase()})`;
const kScheme = (mode) =>
  Object.entries(tokens.color[mode])
    .map(([k, v]) => `        val ${k} = ${kColor(v)}`)
    .join("\n");
const kotlin = `// ${header}
package net.soundpush.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object Tokens {
    object Light {
${kScheme("light")}
    }

    object Dark {
${kScheme("dark")}
    }

    object Space {
${Object.entries(tokens.spacing).map(([k, v]) => `        val ${k} = ${v}.dp`).join("\n")}
    }

    object Radius {
${Object.entries(tokens.radius).map(([k, v]) => `        val ${k} = ${Math.min(v, 999)}.dp`).join("\n")}
    }

    object Type {
${Object.entries(tokens.typography)
  .map(([k, v]) => `        val ${k}Size = ${v.size}.sp\n        val ${k}Line = ${v.lineHeight}.sp\n        const val ${k}Weight = ${v.weight}`)
  .join("\n")}
    }

    object Motion {
${Object.entries(tokens.motion).map(([k, v]) => `        const val ${k} = ${v}`).join("\n")}
    }
}
`;
const ktPath = join(root, "sound-push-mobile/android/core-ui/src/main/java/net/soundpush/ui/theme/Tokens.kt");
mkdirSync(dirname(ktPath), { recursive: true });
writeFileSync(ktPath, kotlin);

console.log("tokens generated: CSS + Kotlin (contrast checks passed)");
